# Generated by Django 5.2 on 2025-05-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fitness_goal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
