# Generated by Django 5.2 on 2025-05-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_fitness_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
