# Generated by Django 5.2 on 2025-05-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_site_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fat_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
